// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_base_kit/test/features/login/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:flutter_kit_auth/auth/bloc/auth_status.dart' as _i14;
import 'package:flutter_kit_auth/auth/domain/entity/auth_entity.dart' as _i18;
import 'package:flutter_kit_auth/auth/domain/enum/social_auth_provider.dart'
    as _i19;
import 'package:flutter_kit_auth/auth/domain/usecase/guest_sign_in_usecase.dart'
    as _i9;
import 'package:flutter_kit_auth/auth/domain/usecase/login_usecase.dart' as _i2;
import 'package:flutter_kit_auth/auth/domain/usecase/logout_usecase.dart'
    as _i6;
import 'package:flutter_kit_auth/auth/domain/usecase/me_usecase.dart' as _i4;
import 'package:flutter_kit_auth/auth/domain/usecase/password_reset_usecase.dart'
    as _i10;
import 'package:flutter_kit_auth/auth/domain/usecase/refresh_usecase.dart'
    as _i7;
import 'package:flutter_kit_auth/auth/domain/usecase/register_usecase.dart'
    as _i3;
import 'package:flutter_kit_auth/auth/domain/usecase/social_sign_in_usecase.dart'
    as _i8;
import 'package:flutter_kit_auth/auth/domain/usecase/update_profile_usecase.dart'
    as _i5;
import 'package:flutter_kit_auth/auth/manager/auth_manager.dart' as _i12;
import 'package:flutter_kit_auth/auth/token/token_store.dart' as _i11;
import 'package:flutter_kit_network/core/network/error/api_error.dart' as _i16;
import 'package:flutter_kit_network/core/utils/result.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginUseCase_0 extends _i1.SmartFake implements _i2.LoginUseCase {
  _FakeLoginUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterUseCase_1 extends _i1.SmartFake
    implements _i3.RegisterUseCase {
  _FakeRegisterUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMeUseCase_2 extends _i1.SmartFake implements _i4.MeUseCase {
  _FakeMeUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProfileUseCase_3 extends _i1.SmartFake
    implements _i5.UpdateProfileUseCase {
  _FakeUpdateProfileUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutUseCase_4 extends _i1.SmartFake implements _i6.LogoutUseCase {
  _FakeLogoutUseCase_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRefreshUseCase_5 extends _i1.SmartFake
    implements _i7.RefreshUseCase {
  _FakeRefreshUseCase_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSocialSignInUseCase_6 extends _i1.SmartFake
    implements _i8.SocialSignInUseCase {
  _FakeSocialSignInUseCase_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGuestSignInUseCase_7 extends _i1.SmartFake
    implements _i9.GuestSignInUseCase {
  _FakeGuestSignInUseCase_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartPasswordResetUseCase_8 extends _i1.SmartFake
    implements _i10.StartPasswordResetUseCase {
  _FakeStartPasswordResetUseCase_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyPasswordResetUseCase_9 extends _i1.SmartFake
    implements _i10.VerifyPasswordResetUseCase {
  _FakeVerifyPasswordResetUseCase_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompletePasswordResetUseCase_10 extends _i1.SmartFake
    implements _i10.CompletePasswordResetUseCase {
  _FakeCompletePasswordResetUseCase_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeTokenStore_11 extends _i1.SmartFake implements _i11.TokenStore {
  _FakeTokenStore_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthManager extends _i1.Mock implements _i12.AuthManager {
  @override
  _i2.LoginUseCase get loginUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#loginUseCase),
            returnValue: _FakeLoginUseCase_0(
              this,
              Invocation.getter(#loginUseCase),
            ),
            returnValueForMissingStub: _FakeLoginUseCase_0(
              this,
              Invocation.getter(#loginUseCase),
            ),
          )
          as _i2.LoginUseCase);

  @override
  _i3.RegisterUseCase get registerUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#registerUseCase),
            returnValue: _FakeRegisterUseCase_1(
              this,
              Invocation.getter(#registerUseCase),
            ),
            returnValueForMissingStub: _FakeRegisterUseCase_1(
              this,
              Invocation.getter(#registerUseCase),
            ),
          )
          as _i3.RegisterUseCase);

  @override
  _i4.MeUseCase get meUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#meUseCase),
            returnValue: _FakeMeUseCase_2(this, Invocation.getter(#meUseCase)),
            returnValueForMissingStub: _FakeMeUseCase_2(
              this,
              Invocation.getter(#meUseCase),
            ),
          )
          as _i4.MeUseCase);

  @override
  _i5.UpdateProfileUseCase get updateProfileUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#updateProfileUseCase),
            returnValue: _FakeUpdateProfileUseCase_3(
              this,
              Invocation.getter(#updateProfileUseCase),
            ),
            returnValueForMissingStub: _FakeUpdateProfileUseCase_3(
              this,
              Invocation.getter(#updateProfileUseCase),
            ),
          )
          as _i5.UpdateProfileUseCase);

  @override
  _i6.LogoutUseCase get logoutUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#logoutUseCase),
            returnValue: _FakeLogoutUseCase_4(
              this,
              Invocation.getter(#logoutUseCase),
            ),
            returnValueForMissingStub: _FakeLogoutUseCase_4(
              this,
              Invocation.getter(#logoutUseCase),
            ),
          )
          as _i6.LogoutUseCase);

  @override
  _i7.RefreshUseCase get refreshUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#refreshUseCase),
            returnValue: _FakeRefreshUseCase_5(
              this,
              Invocation.getter(#refreshUseCase),
            ),
            returnValueForMissingStub: _FakeRefreshUseCase_5(
              this,
              Invocation.getter(#refreshUseCase),
            ),
          )
          as _i7.RefreshUseCase);

  @override
  _i8.SocialSignInUseCase get socialSignInUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#socialSignInUseCase),
            returnValue: _FakeSocialSignInUseCase_6(
              this,
              Invocation.getter(#socialSignInUseCase),
            ),
            returnValueForMissingStub: _FakeSocialSignInUseCase_6(
              this,
              Invocation.getter(#socialSignInUseCase),
            ),
          )
          as _i8.SocialSignInUseCase);

  @override
  _i9.GuestSignInUseCase get guestSignInUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#guestSignInUseCase),
            returnValue: _FakeGuestSignInUseCase_7(
              this,
              Invocation.getter(#guestSignInUseCase),
            ),
            returnValueForMissingStub: _FakeGuestSignInUseCase_7(
              this,
              Invocation.getter(#guestSignInUseCase),
            ),
          )
          as _i9.GuestSignInUseCase);

  @override
  _i10.StartPasswordResetUseCase get startPasswordResetUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#startPasswordResetUseCase),
            returnValue: _FakeStartPasswordResetUseCase_8(
              this,
              Invocation.getter(#startPasswordResetUseCase),
            ),
            returnValueForMissingStub: _FakeStartPasswordResetUseCase_8(
              this,
              Invocation.getter(#startPasswordResetUseCase),
            ),
          )
          as _i10.StartPasswordResetUseCase);

  @override
  _i10.VerifyPasswordResetUseCase get verifyPasswordResetUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#verifyPasswordResetUseCase),
            returnValue: _FakeVerifyPasswordResetUseCase_9(
              this,
              Invocation.getter(#verifyPasswordResetUseCase),
            ),
            returnValueForMissingStub: _FakeVerifyPasswordResetUseCase_9(
              this,
              Invocation.getter(#verifyPasswordResetUseCase),
            ),
          )
          as _i10.VerifyPasswordResetUseCase);

  @override
  _i10.CompletePasswordResetUseCase get completePasswordResetUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#completePasswordResetUseCase),
            returnValue: _FakeCompletePasswordResetUseCase_10(
              this,
              Invocation.getter(#completePasswordResetUseCase),
            ),
            returnValueForMissingStub: _FakeCompletePasswordResetUseCase_10(
              this,
              Invocation.getter(#completePasswordResetUseCase),
            ),
          )
          as _i10.CompletePasswordResetUseCase);

  @override
  _i11.TokenStore get tokenStore =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStore),
            returnValue: _FakeTokenStore_11(
              this,
              Invocation.getter(#tokenStore),
            ),
            returnValueForMissingStub: _FakeTokenStore_11(
              this,
              Invocation.getter(#tokenStore),
            ),
          )
          as _i11.TokenStore);

  @override
  _i13.Stream<_i14.AuthStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i13.Stream<_i14.AuthStatus>.empty(),
            returnValueForMissingStub: _i13.Stream<_i14.AuthStatus>.empty(),
          )
          as _i13.Stream<_i14.AuthStatus>);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isBusy =>
      (super.noSuchMethod(
            Invocation.getter(#isBusy),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#login, [email, password]),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> register({
    required String? email,
    required String? password,
    String? firstName,
    String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #password: password,
                  #firstName: firstName,
                  #lastName: lastName,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#register, [], {
                      #email: email,
                      #password: password,
                      #firstName: firstName,
                      #lastName: lastName,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> fetchMe() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMe, []),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#fetchMe, []),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#fetchMe, []),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> updateProfile(
    Map<String, dynamic>? patch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [patch]),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#updateProfile, [patch]),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#updateProfile, [patch]),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<void> saveTokens(_i18.AuthTokens? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [tokens]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#logout, []),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<_i18.AuthTokens?, _i16.ApiError>> refreshIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#refreshIfNeeded, []),
            returnValue:
                _i13.Future<_i15.Result<_i18.AuthTokens?, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<_i18.AuthTokens?, _i16.ApiError>>(
                    this,
                    Invocation.method(#refreshIfNeeded, []),
                  ),
                ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<_i18.AuthTokens?, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<_i18.AuthTokens?, _i16.ApiError>>(
                    this,
                    Invocation.method(#refreshIfNeeded, []),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<_i18.AuthTokens?, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> signInWithSocial(
    _i19.SocialAuthProvider? provider,
    String? idToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithSocial, [provider, idToken]),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#signInWithSocial, [provider, idToken]),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#signInWithSocial, [provider, idToken]),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> signInAsGuest() =>
      (super.noSuchMethod(
            Invocation.method(#signInAsGuest, []),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#signInAsGuest, []),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#signInAsGuest, []),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> startPasswordReset(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startPasswordReset, [email]),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#startPasswordReset, [email]),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#startPasswordReset, [email]),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> verifyPasswordReset({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordReset, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#verifyPasswordReset, [], {
                  #email: email,
                  #code: code,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#verifyPasswordReset, [], {
                      #email: email,
                      #code: code,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);

  @override
  _i13.Future<_i15.Result<void, _i16.ApiError>> completePasswordReset({
    required String? email,
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completePasswordReset, [], {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
              _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                this,
                Invocation.method(#completePasswordReset, [], {
                  #email: email,
                  #code: code,
                  #newPassword: newPassword,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i15.Result<void, _i16.ApiError>>.value(
                  _i17.dummyValue<_i15.Result<void, _i16.ApiError>>(
                    this,
                    Invocation.method(#completePasswordReset, [], {
                      #email: email,
                      #code: code,
                      #newPassword: newPassword,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i15.Result<void, _i16.ApiError>>);
}
