import 'country_phone.dart';

/// Türkiye — every phone field starts here, because that is the app's market.
/// A user roaming abroad keeps `+90` rather than picking up the SIM's region.
const defaultCountryPhone = CountryPhone(
  isoCode: 'TR',
  dialCode: '+90',
  pattern: '### ### ## ##',
  nameTr: 'Türkiye',
  nameEn: 'Turkey',
  trunkPrefix: '0',
  mobilePrefixes: ['5'],
);

/// Country dial codes and national-number masks, ported from the iOS app's
/// `DesignSystem/Utilities/Country.swift` so both platforms format and
/// validate identically.
///
/// Scope: the 231 entries whose ISO 3166-1 alpha-2 code is officially assigned
/// and that own that code. Dropped from the iOS list were organisations
/// (EU, UN, NATO), sub-national regions that reuse their parent's code
/// (England, Basque Country, Canary Islands, Hawaii, Tibet…) and entities with
/// unassigned codes (Abkhazia, Ossetia).
///
/// Two caveats carried over from the source table:
///  * `trunkPrefix` is only filled in for Türkiye — the domestic dialling
///    prefix of other countries was not verified, so a leading 0 is kept
///    verbatim there rather than guessed at.
///  * Masks are fixed-length. Countries whose real numbering plan has variable
///    length are represented by their most common form.
const countryPhoneData = <CountryPhone>[
  CountryPhone(
    isoCode: 'AD',
    dialCode: '+376',
    pattern: '### ###',
    nameTr: 'Andorra',
    nameEn: 'Andorra',
  ),
  CountryPhone(
    isoCode: 'AE',
    dialCode: '+971',
    pattern: '## ### ####',
    nameTr: 'Birleşik Arap Emirlikleri',
    nameEn: 'United Arab Emirates',
  ),
  CountryPhone(
    isoCode: 'AF',
    dialCode: '+93',
    pattern: '## ### ####',
    nameTr: 'Afganistan',
    nameEn: 'Afghanistan',
  ),
  CountryPhone(
    isoCode: 'AG',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Antigua ve Barbuda',
    nameEn: 'Antigua and Barbuda',
  ),
  CountryPhone(
    isoCode: 'AI',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Anguilla',
    nameEn: 'Anguilla',
  ),
  CountryPhone(
    isoCode: 'AL',
    dialCode: '+355',
    pattern: '## ### ####',
    nameTr: 'Arnavutluk',
    nameEn: 'Albania',
  ),
  CountryPhone(
    isoCode: 'AM',
    dialCode: '+374',
    pattern: '## ######',
    nameTr: 'Ermenistan',
    nameEn: 'Armenia',
  ),
  CountryPhone(
    isoCode: 'AO',
    dialCode: '+244',
    pattern: '### ### ###',
    nameTr: 'Angola',
    nameEn: 'Angola',
  ),
  CountryPhone(
    isoCode: 'AR',
    dialCode: '+54',
    pattern: '## ####-####',
    nameTr: 'Arjantin',
    nameEn: 'Argentina',
  ),
  CountryPhone(
    isoCode: 'AS',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Amerikan Samoası',
    nameEn: 'American Samoa',
  ),
  CountryPhone(
    isoCode: 'AT',
    dialCode: '+43',
    pattern: '#### ### ###',
    nameTr: 'Avusturya',
    nameEn: 'Austria',
  ),
  CountryPhone(
    isoCode: 'AU',
    dialCode: '+61',
    pattern: '## #### #####',
    nameTr: 'Avustralya',
    nameEn: 'Australia',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'AW',
    dialCode: '+297',
    pattern: '### ####',
    nameTr: 'Aruba',
    nameEn: 'Aruba',
  ),
  CountryPhone(
    isoCode: 'AX',
    dialCode: '+358',
    pattern: '## ### ####',
    nameTr: 'Åland Adaları',
    nameEn: 'Åland Islands',
  ),
  CountryPhone(
    isoCode: 'AZ',
    dialCode: '+994',
    pattern: '## ### ## ##',
    nameTr: 'Azerbaycan',
    nameEn: 'Azerbaijan',
  ),
  CountryPhone(
    isoCode: 'BA',
    dialCode: '+387',
    pattern: '## ###-###',
    nameTr: 'Bosna Hersek',
    nameEn: 'Bosnia and Herzegovina',
  ),
  CountryPhone(
    isoCode: 'BB',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Barbados',
    nameEn: 'Barbados',
  ),
  CountryPhone(
    isoCode: 'BD',
    dialCode: '+880',
    pattern: '#-##########',
    nameTr: 'Bangladeş',
    nameEn: 'Bangladesh',
  ),
  CountryPhone(
    isoCode: 'BE',
    dialCode: '+32',
    pattern: '### ## ## ##',
    nameTr: 'Belçika',
    nameEn: 'Belgium',
  ),
  CountryPhone(
    isoCode: 'BF',
    dialCode: '+226',
    pattern: '## ## ## ##',
    nameTr: 'Burkina Faso',
    nameEn: 'Burkina Faso',
  ),
  CountryPhone(
    isoCode: 'BG',
    dialCode: '+359',
    pattern: '### ### ###',
    nameTr: 'Bulgaristan',
    nameEn: 'Bulgaria',
  ),
  CountryPhone(
    isoCode: 'BH',
    dialCode: '+973',
    pattern: '#### ####',
    nameTr: 'Bahreyn',
    nameEn: 'Bahrain',
  ),
  CountryPhone(
    isoCode: 'BI',
    dialCode: '+257',
    pattern: '## ## ## ##',
    nameTr: 'Burundi',
    nameEn: 'Burundi',
  ),
  CountryPhone(
    isoCode: 'BJ',
    dialCode: '+229',
    pattern: '## ## ## ##',
    nameTr: 'Benin',
    nameEn: 'Benin',
  ),
  CountryPhone(
    isoCode: 'BL',
    dialCode: '+590',
    pattern: '### ## ## ##',
    nameTr: 'St. Barthelemy',
    nameEn: 'St. Barthélemy',
  ),
  CountryPhone(
    isoCode: 'BM',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Bermuda',
    nameEn: 'Bermuda',
  ),
  CountryPhone(
    isoCode: 'BN',
    dialCode: '+673',
    pattern: '### ####',
    nameTr: 'Brunei',
    nameEn: 'Brunei',
  ),
  CountryPhone(
    isoCode: 'BO',
    dialCode: '+591',
    pattern: '# ### ####',
    nameTr: 'Bolivya',
    nameEn: 'Bolivia',
  ),
  CountryPhone(
    isoCode: 'BQ',
    dialCode: '+599',
    pattern: '### ####',
    nameTr: 'Bonaire',
    nameEn: 'Bonaire',
  ),
  CountryPhone(
    isoCode: 'BR',
    dialCode: '+55',
    pattern: '(##) # ####-####',
    nameTr: 'Brezilya',
    nameEn: 'Brazil',
  ),
  CountryPhone(
    isoCode: 'BS',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Bahamalar',
    nameEn: 'Bahamas',
  ),
  CountryPhone(
    isoCode: 'BT',
    dialCode: '+975',
    pattern: '# ### ###',
    nameTr: 'Bhutan',
    nameEn: 'Bhutan',
  ),
  CountryPhone(
    isoCode: 'BW',
    dialCode: '+267',
    pattern: '## ### ###',
    nameTr: 'Botsvana',
    nameEn: 'Botswana',
  ),
  CountryPhone(
    isoCode: 'BY',
    dialCode: '+375',
    pattern: '## ###-##-##',
    nameTr: 'Belarus',
    nameEn: 'Belarus',
  ),
  CountryPhone(
    isoCode: 'BZ',
    dialCode: '+501',
    pattern: '###-####',
    nameTr: 'Belize',
    nameEn: 'Belize',
  ),
  CountryPhone(
    isoCode: 'CA',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Kanada',
    nameEn: 'Canada',
  ),
  CountryPhone(
    isoCode: 'CC',
    dialCode: '+61',
    pattern: '## #### ####',
    nameTr: 'Cocos Adaları',
    nameEn: 'Cocos Island',
  ),
  CountryPhone(
    isoCode: 'CD',
    dialCode: '+243',
    pattern: '## ### ####',
    nameTr: 'Demokratik Kongo Cumhuriyeti',
    nameEn: 'Democratic Republic of Congo',
  ),
  CountryPhone(
    isoCode: 'CF',
    dialCode: '+236',
    pattern: '## ## ## ##',
    nameTr: 'Orta Afrika Cumhuriyeti',
    nameEn: 'Central African Republic',
  ),
  CountryPhone(
    isoCode: 'CG',
    dialCode: '+242',
    pattern: '## ### ####',
    nameTr: 'Kongo Cumhuriyeti',
    nameEn: 'Republic of the Congo',
  ),
  CountryPhone(
    isoCode: 'CH',
    dialCode: '+41',
    pattern: '## ### ## ##',
    nameTr: 'İsviçre',
    nameEn: 'Switzerland',
  ),
  CountryPhone(
    isoCode: 'CI',
    dialCode: '+225',
    pattern: '## ## ## ##',
    nameTr: 'Fildişi Sahili',
    nameEn: 'Ivory Coast',
  ),
  CountryPhone(
    isoCode: 'CK',
    dialCode: '+682',
    pattern: '## ###',
    nameTr: 'Cook Adaları',
    nameEn: 'Cook Islands',
  ),
  CountryPhone(
    isoCode: 'CL',
    dialCode: '+56',
    pattern: '# #### ####',
    nameTr: 'Şili',
    nameEn: 'Chile',
  ),
  CountryPhone(
    isoCode: 'CM',
    dialCode: '+237',
    pattern: '# ## ## ## ##',
    nameTr: 'Kamerun',
    nameEn: 'Cameroon',
  ),
  CountryPhone(
    isoCode: 'CN',
    dialCode: '+86',
    pattern: '### #### ####',
    nameTr: 'Çin',
    nameEn: 'China',
  ),
  CountryPhone(
    isoCode: 'CO',
    dialCode: '+57',
    pattern: '### ### ####',
    nameTr: 'Kolombiya',
    nameEn: 'Colombia',
  ),
  CountryPhone(
    isoCode: 'CR',
    dialCode: '+506',
    pattern: '#### ####',
    nameTr: 'Kosta Rika',
    nameEn: 'Costa Rica',
  ),
  CountryPhone(
    isoCode: 'CU',
    dialCode: '+53',
    pattern: '# ### ####',
    nameTr: 'Küba',
    nameEn: 'Cuba',
  ),
  CountryPhone(
    isoCode: 'CV',
    dialCode: '+238',
    pattern: '### ## ##',
    nameTr: 'Yeşil Burun Adaları',
    nameEn: 'Cape Verde',
  ),
  CountryPhone(
    isoCode: 'CW',
    dialCode: '+599',
    pattern: '# ### ####',
    nameTr: 'Curaçao',
    nameEn: 'Curaçao',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'CY',
    dialCode: '+357',
    pattern: '## ### ###',
    nameTr: 'Kıbrıs',
    nameEn: 'Cyprus',
  ),
  CountryPhone(
    isoCode: 'CZ',
    dialCode: '+420',
    pattern: '### ### ###',
    nameTr: 'Çek Cumhuriyeti',
    nameEn: 'Czech Republic',
  ),
  CountryPhone(
    isoCode: 'DE',
    dialCode: '+49',
    pattern: '### ########',
    nameTr: 'Almanya',
    nameEn: 'Germany',
  ),
  CountryPhone(
    isoCode: 'DJ',
    dialCode: '+253',
    pattern: '## ## ## ##',
    nameTr: 'Cibuti',
    nameEn: 'Djibouti',
  ),
  CountryPhone(
    isoCode: 'DK',
    dialCode: '+45',
    pattern: '## ## ## ##',
    nameTr: 'Danimarka',
    nameEn: 'Denmark',
  ),
  CountryPhone(
    isoCode: 'DM',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Dominika',
    nameEn: 'Dominica',
  ),
  CountryPhone(
    isoCode: 'DO',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Dominik Cumhuriyeti',
    nameEn: 'Dominican Republic',
  ),
  CountryPhone(
    isoCode: 'DZ',
    dialCode: '+213',
    pattern: '# ## ## ## ##',
    nameTr: 'Cezayir',
    nameEn: 'Algeria',
  ),
  CountryPhone(
    isoCode: 'EC',
    dialCode: '+593',
    pattern: '## ### ####',
    nameTr: 'Ekvador',
    nameEn: 'Ecuador',
  ),
  CountryPhone(
    isoCode: 'EE',
    dialCode: '+372',
    pattern: '### ####',
    nameTr: 'Estonya',
    nameEn: 'Estonia',
  ),
  CountryPhone(
    isoCode: 'EG',
    dialCode: '+20',
    pattern: '### ### ####',
    nameTr: 'Mısır',
    nameEn: 'Egypt',
  ),
  CountryPhone(
    isoCode: 'EH',
    dialCode: '+212',
    pattern: '## ## ## ##',
    nameTr: 'Sahra Demokratik Arap Cumhuriyeti',
    nameEn: 'Sahrawi Arab Democratic Republic',
  ),
  CountryPhone(
    isoCode: 'ER',
    dialCode: '+291',
    pattern: '# ### ###',
    nameTr: 'Eritre',
    nameEn: 'Eritrea',
  ),
  CountryPhone(
    isoCode: 'ES',
    dialCode: '+34',
    pattern: '### ## ## ##',
    nameTr: 'İspanya',
    nameEn: 'Spain',
  ),
  CountryPhone(
    isoCode: 'ET',
    dialCode: '+251',
    pattern: '## ### ####',
    nameTr: 'Etiyopya',
    nameEn: 'Ethiopia',
  ),
  CountryPhone(
    isoCode: 'FI',
    dialCode: '+358',
    pattern: '## ### ####',
    nameTr: 'Finlandiya',
    nameEn: 'Finland',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'FJ',
    dialCode: '+679',
    pattern: '### ####',
    nameTr: 'Fiji',
    nameEn: 'Fiji',
  ),
  CountryPhone(
    isoCode: 'FK',
    dialCode: '+500',
    pattern: '#####',
    nameTr: 'Falkland Adaları',
    nameEn: 'Falkland Islands',
  ),
  CountryPhone(
    isoCode: 'FM',
    dialCode: '+691',
    pattern: '### ####',
    nameTr: 'Mikronezya',
    nameEn: 'Micronesia',
  ),
  CountryPhone(
    isoCode: 'FO',
    dialCode: '+298',
    pattern: '### ###',
    nameTr: 'Faroe Adaları',
    nameEn: 'Faroe Islands',
  ),
  CountryPhone(
    isoCode: 'FR',
    dialCode: '+33',
    pattern: '# ## ## ## ###',
    nameTr: 'Fransa',
    nameEn: 'France',
  ),
  CountryPhone(
    isoCode: 'GA',
    dialCode: '+241',
    pattern: '# ## ## ##',
    nameTr: 'Gabon',
    nameEn: 'Gabon',
  ),
  CountryPhone(
    isoCode: 'GB',
    dialCode: '+44',
    pattern: '#### ######',
    nameTr: 'Birleşik Krallık',
    nameEn: 'United Kingdom',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'GD',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Grenada',
    nameEn: 'Grenada',
  ),
  CountryPhone(
    isoCode: 'GE',
    dialCode: '+995',
    pattern: '### ## ## ##',
    nameTr: 'Gürcistan',
    nameEn: 'Georgia',
  ),
  CountryPhone(
    isoCode: 'GG',
    dialCode: '+44',
    pattern: '#### ######',
    nameTr: 'Guernsey',
    nameEn: 'Guernsey',
  ),
  CountryPhone(
    isoCode: 'GH',
    dialCode: '+233',
    pattern: '## ### ####',
    nameTr: 'Gana',
    nameEn: 'Ghana',
  ),
  CountryPhone(
    isoCode: 'GI',
    dialCode: '+350',
    pattern: '### #####',
    nameTr: 'Cebelitarık',
    nameEn: 'Gibraltar',
  ),
  CountryPhone(
    isoCode: 'GL',
    dialCode: '+299',
    pattern: '## ## ##',
    nameTr: 'Grönland',
    nameEn: 'Greenland',
  ),
  CountryPhone(
    isoCode: 'GM',
    dialCode: '+220',
    pattern: '### ####',
    nameTr: 'Gambiya',
    nameEn: 'Gambia',
  ),
  CountryPhone(
    isoCode: 'GN',
    dialCode: '+224',
    pattern: '## ### ###',
    nameTr: 'Gine',
    nameEn: 'Guinea',
  ),
  CountryPhone(
    isoCode: 'GQ',
    dialCode: '+240',
    pattern: '## ### ####',
    nameTr: 'Ekvator Ginesi',
    nameEn: 'Equatorial Guinea',
  ),
  CountryPhone(
    isoCode: 'GR',
    dialCode: '+30',
    pattern: '### ### ####',
    nameTr: 'Yunanistan',
    nameEn: 'Greece',
  ),
  CountryPhone(
    isoCode: 'GT',
    dialCode: '+502',
    pattern: '#### ####',
    nameTr: 'Guatemala',
    nameEn: 'Guatemala',
  ),
  CountryPhone(
    isoCode: 'GU',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Guam',
    nameEn: 'Guam',
  ),
  CountryPhone(
    isoCode: 'GW',
    dialCode: '+245',
    pattern: '### ####',
    nameTr: 'Gine-Bissau',
    nameEn: 'Guinea-Bissau',
  ),
  CountryPhone(
    isoCode: 'GY',
    dialCode: '+592',
    pattern: '### ####',
    nameTr: 'Guyana',
    nameEn: 'Guyana',
  ),
  CountryPhone(
    isoCode: 'HK',
    dialCode: '+852',
    pattern: '#### ####',
    nameTr: 'Hong Kong',
    nameEn: 'Hong Kong',
  ),
  CountryPhone(
    isoCode: 'HN',
    dialCode: '+504',
    pattern: '#### ####',
    nameTr: 'Honduras',
    nameEn: 'Honduras',
  ),
  CountryPhone(
    isoCode: 'HR',
    dialCode: '+385',
    pattern: '## ### ####',
    nameTr: 'Hırvatistan',
    nameEn: 'Croatia',
  ),
  CountryPhone(
    isoCode: 'HT',
    dialCode: '+509',
    pattern: '## ## ####',
    nameTr: 'Haiti',
    nameEn: 'Haiti',
  ),
  CountryPhone(
    isoCode: 'HU',
    dialCode: '+36',
    pattern: '## ### ####',
    nameTr: 'Macaristan',
    nameEn: 'Hungary',
  ),
  CountryPhone(
    isoCode: 'ID',
    dialCode: '+62',
    pattern: '### ###-####',
    nameTr: 'Endonezya',
    nameEn: 'Indonesia',
  ),
  CountryPhone(
    isoCode: 'IE',
    dialCode: '+353',
    pattern: '## ### ####',
    nameTr: 'İrlanda',
    nameEn: 'Ireland',
  ),
  CountryPhone(
    isoCode: 'IL',
    dialCode: '+972',
    pattern: '##-###-####',
    nameTr: 'İsrail',
    nameEn: 'Israel',
  ),
  CountryPhone(
    isoCode: 'IM',
    dialCode: '+44',
    pattern: '#### ######',
    nameTr: 'Man Adası',
    nameEn: 'Isle of Man',
  ),
  CountryPhone(
    isoCode: 'IN',
    dialCode: '+91',
    pattern: '##### #####',
    nameTr: 'Hindistan',
    nameEn: 'India',
  ),
  CountryPhone(
    isoCode: 'IO',
    dialCode: '+246',
    pattern: '### ####',
    nameTr: 'Britanya Hint Okyanusu Toprakları',
    nameEn: 'British Indian Ocean Territory',
  ),
  CountryPhone(
    isoCode: 'IQ',
    dialCode: '+964',
    pattern: '### ### ####',
    nameTr: 'Irak',
    nameEn: 'Iraq',
  ),
  CountryPhone(
    isoCode: 'IR',
    dialCode: '+98',
    pattern: '### ### ####',
    nameTr: 'İran',
    nameEn: 'Iran',
  ),
  CountryPhone(
    isoCode: 'IS',
    dialCode: '+354',
    pattern: '### ####',
    nameTr: 'İzlanda',
    nameEn: 'Iceland',
  ),
  CountryPhone(
    isoCode: 'IT',
    dialCode: '+39',
    pattern: '## #### ####',
    nameTr: 'İtalya',
    nameEn: 'Italy',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'JE',
    dialCode: '+44',
    pattern: '#### ######',
    nameTr: 'Jersey',
    nameEn: 'Jersey',
  ),
  CountryPhone(
    isoCode: 'JM',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Jamaika',
    nameEn: 'Jamaica',
  ),
  CountryPhone(
    isoCode: 'JO',
    dialCode: '+962',
    pattern: '# #### ####',
    nameTr: 'Ürdün',
    nameEn: 'Jordan',
  ),
  CountryPhone(
    isoCode: 'JP',
    dialCode: '+81',
    pattern: '##-####-####',
    nameTr: 'Japonya',
    nameEn: 'Japan',
  ),
  CountryPhone(
    isoCode: 'KE',
    dialCode: '+254',
    pattern: '### ### ###',
    nameTr: 'Kenya',
    nameEn: 'Kenya',
  ),
  CountryPhone(
    isoCode: 'KG',
    dialCode: '+996',
    pattern: '### ### ###',
    nameTr: 'Kırgızistan',
    nameEn: 'Kyrgyzstan',
  ),
  CountryPhone(
    isoCode: 'KH',
    dialCode: '+855',
    pattern: '## ### ###',
    nameTr: 'Kamboçya',
    nameEn: 'Cambodia',
  ),
  CountryPhone(
    isoCode: 'KI',
    dialCode: '+686',
    pattern: '#### ###',
    nameTr: 'Kiribati',
    nameEn: 'Kiribati',
  ),
  CountryPhone(
    isoCode: 'KM',
    dialCode: '+269',
    pattern: '### ####',
    nameTr: 'Komorlar',
    nameEn: 'Comoros',
  ),
  CountryPhone(
    isoCode: 'KP',
    dialCode: '+850',
    pattern: '### ### ####',
    nameTr: 'Kuzey Kore',
    nameEn: 'North Korea',
  ),
  CountryPhone(
    isoCode: 'KR',
    dialCode: '+82',
    pattern: '##-####-####',
    nameTr: 'Güney Kore',
    nameEn: 'South Korea',
  ),
  CountryPhone(
    isoCode: 'KW',
    dialCode: '+965',
    pattern: '### #####',
    nameTr: 'Kuveyt',
    nameEn: 'Kuwait',
  ),
  CountryPhone(
    isoCode: 'KY',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Cayman Adaları',
    nameEn: 'Cayman Islands',
  ),
  CountryPhone(
    isoCode: 'KZ',
    dialCode: '+7',
    pattern: '### ### ## ##',
    nameTr: 'Kazakistan',
    nameEn: 'Kazakhstan',
  ),
  CountryPhone(
    isoCode: 'LA',
    dialCode: '+856',
    pattern: '## ### ###',
    nameTr: 'Laos',
    nameEn: 'Laos',
  ),
  CountryPhone(
    isoCode: 'LB',
    dialCode: '+961',
    pattern: '# ### ###',
    nameTr: 'Lübnan',
    nameEn: 'Lebanon',
  ),
  CountryPhone(
    isoCode: 'LC',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'St. Lucia',
    nameEn: 'St. Lucia',
  ),
  CountryPhone(
    isoCode: 'LI',
    dialCode: '+423',
    pattern: '### ### ###',
    nameTr: 'Lihtenştayn',
    nameEn: 'Liechtenstein',
  ),
  CountryPhone(
    isoCode: 'LK',
    dialCode: '+94',
    pattern: '## ### ####',
    nameTr: 'Sri Lanka',
    nameEn: 'Sri Lanka',
  ),
  CountryPhone(
    isoCode: 'LR',
    dialCode: '+231',
    pattern: '## ### ###',
    nameTr: 'Liberya',
    nameEn: 'Liberia',
  ),
  CountryPhone(
    isoCode: 'LS',
    dialCode: '+266',
    pattern: '# ### ####',
    nameTr: 'Lesotho',
    nameEn: 'Lesotho',
  ),
  CountryPhone(
    isoCode: 'LT',
    dialCode: '+370',
    pattern: '### #####',
    nameTr: 'Litvanya',
    nameEn: 'Lithuania',
  ),
  CountryPhone(
    isoCode: 'LU',
    dialCode: '+352',
    pattern: '### ### ###',
    nameTr: 'Lüksemburg',
    nameEn: 'Luxembourg',
  ),
  CountryPhone(
    isoCode: 'LV',
    dialCode: '+371',
    pattern: '## ### ###',
    nameTr: 'Letonya',
    nameEn: 'Latvia',
  ),
  CountryPhone(
    isoCode: 'LY',
    dialCode: '+218',
    pattern: '## ### ###',
    nameTr: 'Libya',
    nameEn: 'Libya',
  ),
  CountryPhone(
    isoCode: 'MA',
    dialCode: '+212',
    pattern: '### ## ## ##',
    nameTr: 'Fas',
    nameEn: 'Morocco',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'MC',
    dialCode: '+377',
    pattern: '## ## ## ##',
    nameTr: 'Monako',
    nameEn: 'Monaco',
  ),
  CountryPhone(
    isoCode: 'MD',
    dialCode: '+373',
    pattern: '### ## ###',
    nameTr: 'Moldova',
    nameEn: 'Moldova',
  ),
  CountryPhone(
    isoCode: 'ME',
    dialCode: '+382',
    pattern: '## ### ###',
    nameTr: 'Karadağ',
    nameEn: 'Montenegro',
  ),
  CountryPhone(
    isoCode: 'MG',
    dialCode: '+261',
    pattern: '## ## #####',
    nameTr: 'Madagaskar',
    nameEn: 'Madagascar',
  ),
  CountryPhone(
    isoCode: 'MH',
    dialCode: '+692',
    pattern: '### ####',
    nameTr: 'Marshall Adaları',
    nameEn: 'Marshall Island',
  ),
  CountryPhone(
    isoCode: 'MK',
    dialCode: '+389',
    pattern: '## ### ###',
    nameTr: 'Kuzey Makedonya',
    nameEn: 'Republic of North Macedonia',
  ),
  CountryPhone(
    isoCode: 'ML',
    dialCode: '+223',
    pattern: '## ## ## ##',
    nameTr: 'Mali',
    nameEn: 'Mali',
  ),
  CountryPhone(
    isoCode: 'MM',
    dialCode: '+95',
    pattern: '# ### ###',
    nameTr: 'Myanmar',
    nameEn: 'Myanmar',
  ),
  CountryPhone(
    isoCode: 'MN',
    dialCode: '+976',
    pattern: '## ## ####',
    nameTr: 'Moğolistan',
    nameEn: 'Mongolia',
  ),
  CountryPhone(
    isoCode: 'MO',
    dialCode: '+853',
    pattern: '#### ####',
    nameTr: 'Makao',
    nameEn: 'Macao',
  ),
  CountryPhone(
    isoCode: 'MP',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Kuzey Mariana Adaları',
    nameEn: 'Northern Marianas Islands',
  ),
  CountryPhone(
    isoCode: 'MQ',
    dialCode: '+596',
    pattern: '### ## ## ##',
    nameTr: 'Martinik',
    nameEn: 'Martinique',
  ),
  CountryPhone(
    isoCode: 'MR',
    dialCode: '+222',
    pattern: '## ## ## ##',
    nameTr: 'Moritanya',
    nameEn: 'Mauritania',
  ),
  CountryPhone(
    isoCode: 'MS',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Montserrat',
    nameEn: 'Montserrat',
  ),
  CountryPhone(
    isoCode: 'MT',
    dialCode: '+356',
    pattern: '#### ####',
    nameTr: 'Malta',
    nameEn: 'Malta',
  ),
  CountryPhone(
    isoCode: 'MU',
    dialCode: '+230',
    pattern: '#### ####',
    nameTr: 'Mauritius',
    nameEn: 'Mauritius',
  ),
  CountryPhone(
    isoCode: 'MV',
    dialCode: '+960',
    pattern: '### ####',
    nameTr: 'Maldivler',
    nameEn: 'Maldives',
  ),
  CountryPhone(
    isoCode: 'MW',
    dialCode: '+265',
    pattern: '### ## ##',
    nameTr: 'Malavi',
    nameEn: 'Malawi',
  ),
  CountryPhone(
    isoCode: 'MX',
    dialCode: '+52',
    pattern: '## #### ####',
    nameTr: 'Meksika',
    nameEn: 'Mexico',
  ),
  CountryPhone(
    isoCode: 'MY',
    dialCode: '+60',
    pattern: '##-### ####',
    nameTr: 'Malezya',
    nameEn: 'Malaysia',
  ),
  CountryPhone(
    isoCode: 'MZ',
    dialCode: '+258',
    pattern: '## ### ###',
    nameTr: 'Mozambik',
    nameEn: 'Mozambique',
  ),
  CountryPhone(
    isoCode: 'NA',
    dialCode: '+264',
    pattern: '## ### ####',
    nameTr: 'Namibya',
    nameEn: 'Namibia',
  ),
  CountryPhone(
    isoCode: 'NE',
    dialCode: '+227',
    pattern: '## ## ## ##',
    nameTr: 'Nijer',
    nameEn: 'Niger',
  ),
  CountryPhone(
    isoCode: 'NF',
    dialCode: '+672',
    pattern: '### ###',
    nameTr: 'Norfolk Adası',
    nameEn: 'Norfolk Island',
  ),
  CountryPhone(
    isoCode: 'NG',
    dialCode: '+234',
    pattern: '### ### ####',
    nameTr: 'Nijerya',
    nameEn: 'Nigeria',
  ),
  CountryPhone(
    isoCode: 'NI',
    dialCode: '+505',
    pattern: '#### ####',
    nameTr: 'Nikaragua',
    nameEn: 'Nicaragua',
  ),
  CountryPhone(
    isoCode: 'NL',
    dialCode: '+31',
    pattern: '## ### ## ##',
    nameTr: 'Hollanda',
    nameEn: 'Netherlands',
  ),
  CountryPhone(
    isoCode: 'NO',
    dialCode: '+47',
    pattern: '## ## ## ##',
    nameTr: 'Norveç',
    nameEn: 'Norway',
  ),
  CountryPhone(
    isoCode: 'NP',
    dialCode: '+977',
    pattern: '##-###-####',
    nameTr: 'Nepal',
    nameEn: 'Nepal',
  ),
  CountryPhone(
    isoCode: 'NR',
    dialCode: '+674',
    pattern: '### ####',
    nameTr: 'Nauru',
    nameEn: 'Nauru',
  ),
  CountryPhone(
    isoCode: 'NU',
    dialCode: '+683',
    pattern: '####',
    nameTr: 'Niue',
    nameEn: 'Niue',
  ),
  CountryPhone(
    isoCode: 'NZ',
    dialCode: '+64',
    pattern: '## ### ####',
    nameTr: 'Yeni Zelanda',
    nameEn: 'New Zealand',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'OM',
    dialCode: '+968',
    pattern: '#### ####',
    nameTr: 'Umman',
    nameEn: 'Oman',
  ),
  CountryPhone(
    isoCode: 'PA',
    dialCode: '+507',
    pattern: '### ####',
    nameTr: 'Panama',
    nameEn: 'Panama',
  ),
  CountryPhone(
    isoCode: 'PE',
    dialCode: '+51',
    pattern: '### ### ###',
    nameTr: 'Peru',
    nameEn: 'Peru',
  ),
  CountryPhone(
    isoCode: 'PF',
    dialCode: '+689',
    pattern: '## ## ##',
    nameTr: 'Fransız Polinezyası',
    nameEn: 'French Polynesia',
  ),
  CountryPhone(
    isoCode: 'PG',
    dialCode: '+675',
    pattern: '### ####',
    nameTr: 'Papua Yeni Gine',
    nameEn: 'Papua New Guinea',
  ),
  CountryPhone(
    isoCode: 'PH',
    dialCode: '+63',
    pattern: '### ### ####',
    nameTr: 'Filipinler',
    nameEn: 'Philippines',
  ),
  CountryPhone(
    isoCode: 'PK',
    dialCode: '+92',
    pattern: '### ### ####',
    nameTr: 'Pakistan',
    nameEn: 'Pakistan',
  ),
  CountryPhone(
    isoCode: 'PL',
    dialCode: '+48',
    pattern: '### ### ###',
    nameTr: 'Polonya',
    nameEn: 'Poland',
  ),
  CountryPhone(
    isoCode: 'PN',
    dialCode: '+64',
    pattern: '## ### ####',
    nameTr: 'Pitcairn Adaları',
    nameEn: 'Pitcairn Islands',
  ),
  CountryPhone(
    isoCode: 'PR',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Porto Riko',
    nameEn: 'Puerto Rico',
  ),
  CountryPhone(
    isoCode: 'PS',
    dialCode: '+970',
    pattern: '### ### ###',
    nameTr: 'Filistin',
    nameEn: 'Palestine',
  ),
  CountryPhone(
    isoCode: 'PT',
    dialCode: '+351',
    pattern: '### ### ###',
    nameTr: 'Portekiz',
    nameEn: 'Portugal',
  ),
  CountryPhone(
    isoCode: 'PW',
    dialCode: '+680',
    pattern: '### ####',
    nameTr: 'Palau',
    nameEn: 'Palau',
  ),
  CountryPhone(
    isoCode: 'PY',
    dialCode: '+595',
    pattern: '### ######',
    nameTr: 'Paraguay',
    nameEn: 'Paraguay',
  ),
  CountryPhone(
    isoCode: 'QA',
    dialCode: '+974',
    pattern: '#### ####',
    nameTr: 'Katar',
    nameEn: 'Qatar',
  ),
  CountryPhone(
    isoCode: 'RO',
    dialCode: '+40',
    pattern: '### ### ###',
    nameTr: 'Romanya',
    nameEn: 'Romania',
  ),
  CountryPhone(
    isoCode: 'RS',
    dialCode: '+381',
    pattern: '## ### ####',
    nameTr: 'Sırbistan',
    nameEn: 'Serbia',
  ),
  CountryPhone(
    isoCode: 'RU',
    dialCode: '+7',
    pattern: '(###) ###-##-##',
    nameTr: 'Rusya',
    nameEn: 'Russia',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'RW',
    dialCode: '+250',
    pattern: '### ### ###',
    nameTr: 'Ruanda',
    nameEn: 'Rwanda',
  ),
  CountryPhone(
    isoCode: 'SA',
    dialCode: '+966',
    pattern: '## ### ####',
    nameTr: 'Suudi Arabistan',
    nameEn: 'Saudi Arabia',
  ),
  CountryPhone(
    isoCode: 'SB',
    dialCode: '+677',
    pattern: '### ####',
    nameTr: 'Solomon Adaları',
    nameEn: 'Solomon Islands',
  ),
  CountryPhone(
    isoCode: 'SC',
    dialCode: '+248',
    pattern: '# ### ###',
    nameTr: 'Seyşeller',
    nameEn: 'Seychelles',
  ),
  CountryPhone(
    isoCode: 'SD',
    dialCode: '+249',
    pattern: '## ### ####',
    nameTr: 'Sudan',
    nameEn: 'Sudan',
  ),
  CountryPhone(
    isoCode: 'SE',
    dialCode: '+46',
    pattern: '###-### ## ##',
    nameTr: 'İsveç',
    nameEn: 'Sweden',
  ),
  CountryPhone(
    isoCode: 'SG',
    dialCode: '+65',
    pattern: '#### ####',
    nameTr: 'Singapur',
    nameEn: 'Singapore',
  ),
  CountryPhone(
    isoCode: 'SI',
    dialCode: '+386',
    pattern: '## ### ###',
    nameTr: 'Slovenya',
    nameEn: 'Slovenia',
  ),
  CountryPhone(
    isoCode: 'SK',
    dialCode: '+421',
    pattern: '### ### ###',
    nameTr: 'Slovakya',
    nameEn: 'Slovakia',
  ),
  CountryPhone(
    isoCode: 'SL',
    dialCode: '+232',
    pattern: '## ### ###',
    nameTr: 'Sierra Leone',
    nameEn: 'Sierra Leone',
  ),
  CountryPhone(
    isoCode: 'SM',
    dialCode: '+378',
    pattern: '#### ######',
    nameTr: 'San Marino',
    nameEn: 'San Marino',
  ),
  CountryPhone(
    isoCode: 'SN',
    dialCode: '+221',
    pattern: '## ### ## ##',
    nameTr: 'Senegal',
    nameEn: 'Senegal',
  ),
  CountryPhone(
    isoCode: 'SO',
    dialCode: '+252',
    pattern: '## ### ###',
    nameTr: 'Somali',
    nameEn: 'Somalia',
  ),
  CountryPhone(
    isoCode: 'SR',
    dialCode: '+597',
    pattern: '### ####',
    nameTr: 'Surinam',
    nameEn: 'Suriname',
  ),
  CountryPhone(
    isoCode: 'SS',
    dialCode: '+211',
    pattern: '## ### ####',
    nameTr: 'Güney Sudan',
    nameEn: 'South Sudan',
  ),
  CountryPhone(
    isoCode: 'ST',
    dialCode: '+239',
    pattern: '## #####',
    nameTr: 'Sao Tome ve Principe',
    nameEn: 'São Tomé and Príncipe',
  ),
  CountryPhone(
    isoCode: 'SV',
    dialCode: '+503',
    pattern: '#### ####',
    nameTr: 'El Salvador',
    nameEn: 'El Salvador',
  ),
  CountryPhone(
    isoCode: 'SX',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Sint Maarten',
    nameEn: 'Sint Maarten',
  ),
  CountryPhone(
    isoCode: 'SY',
    dialCode: '+963',
    pattern: '## #### ###',
    nameTr: 'Suriye',
    nameEn: 'Syria',
  ),
  CountryPhone(
    isoCode: 'SZ',
    dialCode: '+268',
    pattern: '## ## ####',
    nameTr: 'Esvatini',
    nameEn: 'Eswatini',
  ),
  CountryPhone(
    isoCode: 'TC',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Turks ve Caicos Adaları',
    nameEn: 'Turks and Caicos Islands',
  ),
  CountryPhone(
    isoCode: 'TG',
    dialCode: '+228',
    pattern: '## ## ## ##',
    nameTr: 'Togo',
    nameEn: 'Togo',
  ),
  CountryPhone(
    isoCode: 'TH',
    dialCode: '+66',
    pattern: '## ### ####',
    nameTr: 'Tayland',
    nameEn: 'Thailand',
  ),
  CountryPhone(
    isoCode: 'TJ',
    dialCode: '+992',
    pattern: '## ### ####',
    nameTr: 'Tacikistan',
    nameEn: 'Tajikistan',
  ),
  CountryPhone(
    isoCode: 'TK',
    dialCode: '+690',
    pattern: '####',
    nameTr: 'Tokelau',
    nameEn: 'Tokelau',
  ),
  CountryPhone(
    isoCode: 'TL',
    dialCode: '+670',
    pattern: '### ####',
    nameTr: 'Doğu Timor',
    nameEn: 'East Timor',
  ),
  CountryPhone(
    isoCode: 'TM',
    dialCode: '+993',
    pattern: '## ## ## ##',
    nameTr: 'Türkmenistan',
    nameEn: 'Turkmenistan',
  ),
  CountryPhone(
    isoCode: 'TN',
    dialCode: '+216',
    pattern: '## ### ###',
    nameTr: 'Tunus',
    nameEn: 'Tunisia',
  ),
  CountryPhone(
    isoCode: 'TO',
    dialCode: '+676',
    pattern: '## ### ##',
    nameTr: 'Tonga',
    nameEn: 'Tonga',
  ),
  defaultCountryPhone,
  CountryPhone(
    isoCode: 'TT',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Trinidad ve Tobago',
    nameEn: 'Trinidad and Tobago',
  ),
  CountryPhone(
    isoCode: 'TV',
    dialCode: '+688',
    pattern: '## ### ##',
    nameTr: 'Tuvalu',
    nameEn: 'Tuvalu',
  ),
  CountryPhone(
    isoCode: 'TW',
    dialCode: '+886',
    pattern: '### ### ###',
    nameTr: 'Tayvan',
    nameEn: 'Taiwan',
  ),
  CountryPhone(
    isoCode: 'TZ',
    dialCode: '+255',
    pattern: '### ### ###',
    nameTr: 'Tanzanya',
    nameEn: 'Tanzania',
  ),
  CountryPhone(
    isoCode: 'UA',
    dialCode: '+380',
    pattern: '## ### ## ##',
    nameTr: 'Ukrayna',
    nameEn: 'Ukraine',
  ),
  CountryPhone(
    isoCode: 'UG',
    dialCode: '+256',
    pattern: '### ### ###',
    nameTr: 'Uganda',
    nameEn: 'Uganda',
  ),
  CountryPhone(
    isoCode: 'US',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Amerika Birleşik Devletleri',
    nameEn: 'United States',
    isDialCodePrimary: true,
  ),
  CountryPhone(
    isoCode: 'UY',
    dialCode: '+598',
    pattern: '# ### ## ##',
    nameTr: 'Uruguay',
    nameEn: 'Uruguay',
  ),
  CountryPhone(
    isoCode: 'UZ',
    dialCode: '+998',
    pattern: '## ### ## ##',
    nameTr: 'Özbekistan',
    nameEn: 'Uzbekistan',
  ),
  CountryPhone(
    isoCode: 'VA',
    dialCode: '+39',
    pattern: '## #### ####',
    nameTr: 'Vatikan',
    nameEn: 'Vatican City',
  ),
  CountryPhone(
    isoCode: 'VC',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'St. Vincent ve Grenadinler',
    nameEn: 'St. Vincent and the Grenadines',
  ),
  CountryPhone(
    isoCode: 'VE',
    dialCode: '+58',
    pattern: '### ### ####',
    nameTr: 'Venezuela',
    nameEn: 'Venezuela',
  ),
  CountryPhone(
    isoCode: 'VG',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Britanya Virjin Adaları',
    nameEn: 'British Virgin Islands',
  ),
  CountryPhone(
    isoCode: 'VI',
    dialCode: '+1',
    pattern: '(###) ###-####',
    nameTr: 'Virgin Adaları',
    nameEn: 'Virgin Islands',
  ),
  CountryPhone(
    isoCode: 'VN',
    dialCode: '+84',
    pattern: '### ### ####',
    nameTr: 'Vietnam',
    nameEn: 'Vietnam',
  ),
  CountryPhone(
    isoCode: 'VU',
    dialCode: '+678',
    pattern: '## #####',
    nameTr: 'Vanuatu',
    nameEn: 'Vanuatu',
  ),
  CountryPhone(
    isoCode: 'WS',
    dialCode: '+685',
    pattern: '## ####',
    nameTr: 'Samoa',
    nameEn: 'Samoa',
  ),
  CountryPhone(
    isoCode: 'XK',
    dialCode: '+383',
    pattern: '## ### ###',
    nameTr: 'Kosova',
    nameEn: 'Kosovo',
  ),
  CountryPhone(
    isoCode: 'YE',
    dialCode: '+967',
    pattern: '### ### ###',
    nameTr: 'Yemen',
    nameEn: 'Yemen',
  ),
  CountryPhone(
    isoCode: 'ZA',
    dialCode: '+27',
    pattern: '## ### ####',
    nameTr: 'Güney Afrika',
    nameEn: 'South Africa',
  ),
  CountryPhone(
    isoCode: 'ZM',
    dialCode: '+260',
    pattern: '## ### ####',
    nameTr: 'Zambiya',
    nameEn: 'Zambia',
  ),
  CountryPhone(
    isoCode: 'ZW',
    dialCode: '+263',
    pattern: '## ### ####',
    nameTr: 'Zimbabve',
    nameEn: 'Zimbabwe',
  ),
];
